version: 2
log-file: /home/phelipe/efmlangserver.log
log-level: 1

tools:
  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-formats:
      - '%f:%l:%c: [%tarning] %m'
      - '%f:%l:%c: [%trror] %m'
    lint-stdin: true

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  lua-luacheck: &lua-luacheck
    lint-command: 'luacheck --no-color ${INPUT}'
    lint-formats:
      - '    %f:%l:%c: %m'
    lint-stdin: true

  lua-lua-format: &lua-lua-format
    format-command: 'lua-format -i'
    format-stdin: true

  python-flake8: &python-flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

languages:
  yaml:
    - <<: *yaml-yamllint

  sh:
    - <<: *sh-shellcheck

  lua:
    - <<: *lua-luacheck
    - <<: *lua-lua-format

  python:
    - <<: *python-flake8
