version: 2
# log-file: /home/phelipe/efmlangserver.log
# log-level: 1
root-markers:
  - .git/
  - package.json

tools:
  eslint_d: &eslint_d
    lint-command: 'eslint_d -f unix --stdin --stdin-filename ${INPUT}'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'
    lint-ignore-exit-code: true
    format-command: 'eslint_d --fix-to-stdout --stdin --stdin-filename=${INPUT}'
    format-stdin: true
    root_markers:
      - package.json

  # js_prettier: &js_prettier
  #   format-command: 'prettier --parser typescript'
  #   format-stdin: true
  #   root-markers:
  #     - .prettierrc

languages:
  javascript:
    - <<: *eslint_d
  javascriptreact:
    - <<: *eslint_d
  javascript.jsx:
    - <<: *eslint_d
  typescript:
    - <<: *eslint_d
  typescript.tsx:
    - <<: *eslint_d
    # - <<: *js_prettier
  typescriptreact:
    - <<: *eslint_d
